In [1]:
!pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openai in /usr/local/lib/python3.7/dist-packages (0.25.0)
Requirement already satisfied: pandas>=1.2.3 in /usr/local/lib/python3.7/dist-packages (from openai) (1.3.5)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /usr/local/lib/python3.7/dist-packages (from openai) (1.2.0.62)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from openai) (4.1.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from openai) (4.64.1)
Requirement already satisfied: openpyxl>=3.0.7 in /usr/local/lib/python3.7/dist-packages (from openai) (3.0.10)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from openai) (2.23.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from openai) (1.21.6)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl>=3.0.7->openai) (1.1.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.3->openai) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.3->openai) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2.3->openai) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->openai) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->openai) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->openai) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->openai) (2.10)

In [2]:
import pandas as pd
import json

In [3]:
f = open("data_main.json")
data = json.load(f)

In [4]:
data_df = pd.json_normalize(data['content'],max_level=1)

In [5]:
data_df

,para_id,content,category,publish_date_ap
0,art_3226621_para_1,"Quidel Corp., San Diego, California (SPE2DE-23...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022"
1,art_3226621_para_2,"Change Healthcare Technologies LLC, Alpharetta...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022"
2,art_3226621_para_3,"Creighton AB Inc., Reidsville, North Carolina,...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022"
3,art_3226621_para_4,"IMT Defense Corporation,* Westerville, Ohio, w...",ARMY,"Nov. 22, 2022"
4,art_3226621_para_5,"SilverStar Consulting Inc.,* Falls Church, Vir...",ARMY,"Nov. 22, 2022"
...,...,...,...,...
4559,art_2771255_para_18,"The Boeing Co., St. Louis, Missouri, is awarde...",NAVY,"Sept. 10, 2021"
4560,art_2771255_para_19,"Georgia Tech Applied Research Corp., Georgia T...",AIR FORCE,"Sept. 10, 2021"
4561,art_2771255_para_20,"Enlighten IT Consulting LLC, Linthicum Heights...",AIR FORCE,"Sept. 10, 2021"
4562,art_2771255_para_21,"Frontier Technology Inc., Beavercreek, Ohio, h...",AIR FORCE,"Sept. 10, 2021"
4563,art_2771255_para_22,*Small business,AIR FORCE,"Sept. 10, 2021"

In [6]:
data_df['context'] = data_df.category + "\n\n" + data_df.content

In [7]:
data_df

,para_id,content,category,publish_date_ap,context
0,art_3226621_para_1,"Quidel Corp., San Diego, California (SPE2DE-23...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022","DEFENSE LOGISTICS AGENCY\n\nQuidel Corp., San ..."
1,art_3226621_para_2,"Change Healthcare Technologies LLC, Alpharetta...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022",DEFENSE LOGISTICS AGENCY\n\nChange Healthcare ...
2,art_3226621_para_3,"Creighton AB Inc., Reidsville, North Carolina,...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022","DEFENSE LOGISTICS AGENCY\n\nCreighton AB Inc.,..."
3,art_3226621_para_4,"IMT Defense Corporation,* Westerville, Ohio, w...",ARMY,"Nov. 22, 2022","ARMY\n\nIMT Defense Corporation,* Westerville,..."
4,art_3226621_para_5,"SilverStar Consulting Inc.,* Falls Church, Vir...",ARMY,"Nov. 22, 2022","ARMY\n\nSilverStar Consulting Inc.,* Falls Chu..."
...,...,...,...,...,...
4559,art_2771255_para_18,"The Boeing Co., St. Louis, Missouri, is awarde...",NAVY,"Sept. 10, 2021","NAVY\n\nThe Boeing Co., St. Louis, Missouri, i..."
4560,art_2771255_para_19,"Georgia Tech Applied Research Corp., Georgia T...",AIR FORCE,"Sept. 10, 2021",AIR FORCE\n\nGeorgia Tech Applied Research Cor...
4561,art_2771255_para_20,"Enlighten IT Consulting LLC, Linthicum Heights...",AIR FORCE,"Sept. 10, 2021","AIR FORCE\n\nEnlighten IT Consulting LLC, Lint..."
4562,art_2771255_para_21,"Frontier Technology Inc., Beavercreek, Ohio, h...",AIR FORCE,"Sept. 10, 2021","AIR FORCE\n\nFrontier Technology Inc., Beaverc..."
4563,art_2771255_para_22,*Small business,AIR FORCE,"Sept. 10, 2021",AIR FORCE\n\n*Small business

In [36]:
new_df = data_df.head(d)
new_df

,para_id,content,category,publish_date_ap,context
0,art_3226621_para_1,"Quidel Corp., San Diego, California (SPE2DE-23...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022","DEFENSE LOGISTICS AGENCY\n\nQuidel Corp., San ..."
1,art_3226621_para_2,"Change Healthcare Technologies LLC, Alpharetta...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022",DEFENSE LOGISTICS AGENCY\n\nChange Healthcare ...
2,art_3226621_para_3,"Creighton AB Inc., Reidsville, North Carolina,...",DEFENSE LOGISTICS AGENCY,"Nov. 22, 2022","DEFENSE LOGISTICS AGENCY\n\nCreighton AB Inc.,..."
3,art_3226621_para_4,"IMT Defense Corporation,* Westerville, Ohio, w...",ARMY,"Nov. 22, 2022","ARMY\n\nIMT Defense Corporation,* Westerville,..."
4,art_3226621_para_5,"SilverStar Consulting Inc.,* Falls Church, Vir...",ARMY,"Nov. 22, 2022","ARMY\n\nSilverStar Consulting Inc.,* Falls Chu..."
...,...,...,...,...,...
295,art_3181029_para_5,*Small business,NAVY,"Oct. 5, 2022",NAVY\n\n*Small business
296,art_3179685_para_1,"Northrop Grumman Systems Corporation, Herndon,...",Army,"Oct. 4, 2022","Army\n\nNorthrop Grumman Systems Corporation, ..."
297,art_3179685_para_2,"Lockheed Martin Corp., Fort Worth, Texas is aw...",Navy,"Oct. 4, 2022","Navy\n\nLockheed Martin Corp., Fort Worth, Tex..."
298,art_3179685_para_3,"Sikorsky Aircraft Corp., a Lockheed Martin Co....",Navy,"Oct. 4, 2022","Navy\n\nSikorsky Aircraft Corp., a Lockheed Ma..."
299,art_3179685_para_4,"Lockheed Martin Aeronautics Co., Fort Worth, T...",Navy,"Oct. 4, 2022","Navy\n\nLockheed Martin Aeronautics Co., Fort ..."

In [37]:
import openai
openai.api_key = "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"
def get_questions(context):
  response = openai.Completion.create(
            engine="davinci-instruct-beta",
            prompt=f"Write questions based on the text below\n\nText: {context}\n\nQuestions:\n1.",
            temperature=0,
            max_tokens=257,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0,
            stop=["\n\n"]
          )
  return response['choices'][0]['text']


new_df['questions']= new_df.context.apply(get_questions)
new_df['questions'] = "1." + new_df.questions
print(new_df[['questions']].values[0][0])

1. What is the name of the company that is sharing the contract?
2. What is the name of the contract?
3. What is the type of appropriation?
4. What is the performance completion date?

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [38]:
def get_answers(row):
    try:
        response = openai.Completion.create(
            engine="davinci-instruct-beta",
            prompt=f"Write questions based on the text below\n\nText: {row.context}\n\nQuestions:\n{row.questions}\n\nAnswers:\n1.",
            temperature=0,
            max_tokens=257,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0
        )
        return response['choices'][0]['text']
    except Exception as e:
        print (e)
        return ""


new_df['answers']= new_df.apply(get_answers, axis=1)
new_df['answers'] = "1." + new_df.answers
new_df = new_df.dropna().reset_index().drop('index',axis=1)
print(new_df[['answers']].values[0][0])

1. Quidel Corp., San Diego, California
2. SPE2DE-23-D-0009
3. fiscal 2023 defense working capital funds
4. Nov. 21, 2023

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [39]:
new_df.content.values[0]

'Quidel Corp., San Diego, California (SPE2DE-23-D-0009); Access Bio Inc., Somerset, New Jersey (SPE2DE-23-D-0011); iHealth Labs, Sunnydale, California (SPE2DE-23-D-0012); and Orasure Technologies, Bethlehem, Pennsylvania (SPE2DE-23-D-0010), are sharing a maximum $803,000,000 firm-fixed-price, indefinite-delivery/indefinite-quantity contract under solicitation SPE2DE-22-R-0013 for the procurement of over-the-counter rapid antigen COVID-19 test kits. This was a competitive acquisition with 13 responses received. These are one-year contracts with no option periods. The performance completion date is Nov. 21, 2023. Using customer is Department of Health and Human Services. Type of appropriation is fiscal 2023 defense working capital funds, using funds that were allocated to the Department of Health and Human Services in September 2022. The contracting activity is the Defense Logistics Agency Troop Support, Philadelphia, Pennsylvania.'